---
###############################################################################
# Manager Roundcube Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   roundcube_user: string roundcube username.
#   roundcube_group: string roundcube group.
#   roundcube_create_user: boolean true to create role default user.
#   roundcube_default_user: dict containing builitin.user options for roundcube.
#   roundcube_default_group: dict containing builitin.group options for roundcube.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ roundcube_user }}'
  register: _roundcube_user_exists
  changed_when: _roundcube_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ roundcube_group }}'
  register: _roundcube_group_exists
  changed_when: _roundcube_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create roundcube group'
  ansible.builtin.group:
    name:  '{{ roundcube_default_group.name }}'
    gid:   '{{ roundcube_default_group.gid }}'
    state: 'present'
  when: roundcube_create_user and _roundcube_group_exists.rc != 0

- name: 'manage users | create roundcube user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ roundcube_default_user.name }}'
    group:           '{{ roundcube_default_user.group }}'
    uid:             '{{ roundcube_default_user.uid }}'
    shell:           '{{ roundcube_default_user.shell }}'
    home:            '{{ roundcube_default_user.home }}'
    comment:         '{{ roundcube_default_user.comment }}'
    create_home:     '{{ roundcube_default_user.create_home }}'
    password:        '{{ roundcube_default_user.password }}'
    password_lock:   '{{ roundcube_default_user.password_lock }}'
    update_password: '{{ roundcube_default_user.update_password }}'
    expires:         '{{ roundcube_default_user.expires }}'
    system:          '{{ roundcube_default_user.system }}'
    state:           'present'
  when: roundcube_create_user and _roundcube_user_exists.rc != 0
