---
###############################################################################
# Roundcube Unpack Github Packages
###############################################################################
# Create versioned roundcube directory and unpack 'complete' archive. Remove
# Uncessary options.
#
# Reference:
# * https://roundcube.net/
# * https://atetux.com/how-to-install-roundcube-webmail-1-4-on-debian-10
# * https://www.linuxbabe.com/ubuntu/install-roundcube-webmail-ubuntu-20-04-apache-nginx

- name: 'unpack | create roundcube directory'
  ansible.builtin.file:
    path:  '{{ _roundcube_install_dir }}'
    owner: 'root'
    group: '{{ roundcube_group }}'
    mode:  0755
    state: 'directory'

- name: 'unpack | unpack archive'
  ansible.builtin.unarchive:
    src:     '{{ _roundcube_archive }}'
    remote_src: true
    dest:    '{{ _roundcube_install_dir }}'
    creates: '{{ _roundcube_install_dir }}/public_html'
    owner:   'root'
    group:   '{{ roundcube_group }}'
    mode:    'o-rwx'
    # Remove the leading 'roundcube-version/' directory in the archive
    extra_opts: '--strip-components=1'
  notify: 'restart nginx-fpm'

- name: 'unpack | cleanup unused archive files'
  ansible.builtin.file:
    path:  '{{ item }}'
    state: 'absent'
  loop:
    - '/var/www/html/index.nginx-debian.html'
    - '{{ _roundcube_install_dir }}/CHANGELOG.md'
    - '{{ _roundcube_install_dir }}/INSTALL'
    - '{{ _roundcube_install_dir }}/installer'
    - '{{ _roundcube_install_dir }}/LICENSE'
    - '{{ _roundcube_install_dir }}/README.md'
    - '{{ _roundcube_install_dir }}/SECURITY.md'
    - '{{ _roundcube_install_dir }}/UPGRADING'
